default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: wanderlist_development

test:
  <<: *default
  database: wanderlist_test


production:
  <<: *default
  database: wanderlist_production
  #username: wanderlist
  #password: <%= ENV['WANDERLIST_DATABASE_PASSWORD'] %>
